[package]
name = "tampolbot"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.5", features = ["http2"] }
tokio = { version = "1.20", features = ["macros", "rt-multi-thread"] }
serde = { version = "1.0", features = ["derive"] }
